name: Download M3U Playlist

on:
  schedule:
    - cron: '*/30 * * * *' # Runs every 30 minutes
  workflow_dispatch:        # Allow manual trigger

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Run PHP Script to Download M3U
        run: php scripts/download_m3u.php

      - name: Commit and Push Updated M3U
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add ultrab_playlist.m3u
          git commit -m "🔁 Auto-update M3U file"
          git push
